--tao CSDL ten la "quanlySPA"
-- code duoi day --

---------hien_san
CREATE TABLE KHACHHANG(
	MAKH NVARCHAR(100),
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH INT NOT NULL,
	NAMSINH DATE NOT NULL,
	DIENTHOAI NVARCHAR(50) NOT NULL,
	PRIMARY KEY (MAKH)
)
CREATE TABLE LIEUTRINH(
	MALT NVARCHAR(100),
	TENLT NVARCHAR(100),
	THOIGIANDT INT,
	GIATIEN INT,
	PRIMARY KEY (MALT)
)
CREATE TABLE CTDT(
	MABS NVARCHAR(100),
	MALT NVARCHAR(100),
	SOHD NVARCHAR(100),
	SOLUONG INT,
	THANHTIENLT INT,
	PRIMARY KEY (MABS,MALT,SOHD)
)
ALTER TABLE CTDT ADD CONSTRAINT fk_CTHD_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTDT ADD CONSTRAINT fk_CTHD_QLBS FOREIGN KEY (MABS) REFERENCES QLBS(MABS)
ALTER TABLE CTDT ADD CONSTRAINT fk_CTHD_LT FOREIGN KEY (MALT) REFERENCES LIEUTRINH(MALT)
----Viz
CREATE TABLE HOADON(
    SOHD NVARCHAR(100),
	MAKH NVARCHAR(100),
	TONGTIEN INT,
	MANV NVARCHAR(100),
	NGAYTAO DATE,
	PRIMARY KEY (SOHD)
)
CREATE TABLE CTHD(
    SOHD NVARCHAR(100),
	MAMP NVARCHAR(100),
	THANHTIENMP INT,
	SOLUONG INT,
	PRIMARY KEY (SOHD,MAMP)
)
CREATE TABLE QLBS(
    MABS NVARCHAR(100),
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH INT NOT NULL,
	SDT NVARCHAR(50) NOT NULL,
	LUONG INT,
	NBDHD DATE NOT NULL,
	NKTHD DATE NOT NULL,
	PRIMARY KEY (MABS)
)
ALTER TABLE HOADON ADD CONSTRAINT fk_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE CTHD ADD CONSTRAINT fk_CTHD_MP FOREIGN KEY(MAMP) REFERENCES MYPHAM(MAMP)
ALTER TABLE CTHD ADD CONSTRAINT fk_CTHD_HD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE HOADON ADD CONSTRAINT fk_HD_QLNV FOREIGN KEY(MANV) REFERENCES QLNV(MANV)


-----Bach san
CREATE TABLE QLNV(
	MANV NVARCHAR(100),
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH INT NOT NULL,
	SDT NVARCHAR(50) NOT NULL,	
	NBDHD DATE NOT NULL,
	NKTHD DATE NOT NULL,
	PASS NVARCHAR(100) NOT NULL,
	LUONG INT,
	PRIMARY KEY (MANV),
)
CREATE TABLE MYPHAM(
	MAMP NVARCHAR(100),
	TENMP NVARCHAR(100) NOT NULL,
	SOLUONGTONKHO INT NOT NULL,
	GIABAN INT NOT NULL, 
	PRIMARY KEY (MAMP),
)


-----Nhan
CREATE TABLE LUONGBS(
	MABS NVARCHAR(100),
	MATT NVARCHAR(100),
	NGAYTT DATE NOT NULL,
	TIENTHUONG INT,
	TONGTIEN INT,
	PRIMARY KEY (MATT)
)

CREATE TABLE LUONGNV(
	MANV NVARCHAR(100),
	MATT NVARCHAR(100),
	NGAYTT DATE NOT NULL,
	TONGTIEN INT,
	PRIMARY KEY (MATT)
)


CREATE TABLE NHAPMP(
	MANMP NVARCHAR(100),
	MAMP NVARCHAR(100),
	DONGIA INT,
	NGAYNHAP DATE NOT NULL,
	SLNHAP INT,
	THANHTIENDH INT,
	MANV NVARCHAR(100),
	PRIMARY KEY (MANMP)
)
ALTER TABLE LUONGBS ADD CONSTRAINT fk_LUONGBS_QLBS FOREIGN KEY (MABS) REFERENCES QLBS(MABS)
ALTER TABLE LUONGNV ADD CONSTRAINT fk_LUONGNV_QLNV FOREIGN KEY (MANV) REFERENCES QLNV(MANV)
ALTER TABLE NHAPMP ADD CONSTRAINT fk_NHAPMP_QLNV FOREIGN KEY (MANV) REFERENCES QLNV(MANV)
ALTER TABLE NHAPMP ADD CONSTRAINT fk_NHAPMP_MYPHAM FOREIGN KEY (MAMP) REFERENCES MYPHAM(MAMP)
