--tao CSDL ten la "quanlySPA"
-- code duoi day --

---------
CREATE TABLE KHACHHANG(
	MAKH NVARCHAR(100),
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH INT NOT NULL,
	NAMSINH DATE NOT NULL,
	TUOI INT,
	QUEQUAN NVARCHAR(100) NOT NULL,
	QUOCTICH NVARCHAR(100),
	DOITUONG NVARCHAR(100),
	DIENTHOAI INT NOT NULL,
	PRIMARY KEY (MAKH)
)
CREATE TABLE LIEUTRINH(
	MALT NVARCHAR(100),
	TENLT NVARCHAR(100),
	THOIGIANDT INT,
	GIATIEN INT,
	PRIMARY KEY (MALT)
)
CREATE TABLE CTDT(
	MABS NVARCHAR(100),
	MAKH NVARCHAR(100),
	MALT NVARCHAR(100),
	TIENTRINH INT,
	PHANTRAMDT INT,
	DATHANHTOAN INT,
	PRIMARY KEY (MABS,MAKH,MALT)
)
----